"""add workspace_id to card, make category_id nullable

Revision ID: 39508c14e6e3
Revises: d651f3de3263
Create Date: 2026-07-12 15:50:08.465042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39508c14e6e3'
down_revision: Union[str, Sequence[str], None] = 'd651f3de3263'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('workspace_id', sa.BigInteger(), nullable=False))
    op.alter_column('card', 'category_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.create_foreign_key(None, 'card', 'workspace', ['workspace_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.alter_column('card', 'category_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('card', 'workspace_id')
    # ### end Alembic commands ###
