"""initial schema

Revision ID: d651f3de3263
Revises: 
Create Date: 2026-07-11 13:25:01.431044

"""
from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd651f3de3263'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('font', sa.String(length=10), server_default='sans-serif', nullable=False),
                    sa.Column('language', sa.String(length=4), server_default='auto', nullable=False),
                    sa.Column('theme', sa.String(length=10), server_default='auto', nullable=False),
                    sa.CheckConstraint("font IN ('serif', 'sans-serif')", name='ck_settings_font'),
                    sa.CheckConstraint("language IN ('ru', 'en', 'auto')", name='ck_settings_language'),
                    sa.CheckConstraint("theme IN ('dark', 'light', 'auto')", name='ck_settings_theme'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user',
                    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
                    sa.Column('email', sa.String(length=320), nullable=False),
                    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('is_superuser', sa.Boolean(), nullable=False),
                    sa.Column('is_verified', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('account',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
                    sa.Column('settings_id', sa.BigInteger(), nullable=False),
                    sa.Column('display_name', sa.String(length=32), nullable=False),
                    sa.CheckConstraint('length(trim(display_name)) > 0', name='ck_account_display_name_not_blank'),
                    sa.ForeignKeyConstraint(['settings_id'], ['settings.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('settings_id'),
                    sa.UniqueConstraint('user_id')
                    )
    op.create_table('workspace',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('name', sa.String(length=24), nullable=False),
                    sa.Column('owner_id', sa.BigInteger(), nullable=False),
                    sa.CheckConstraint('length(trim(name)) > 0', name='ck_workspace_name_not_blank'),
                    sa.ForeignKeyConstraint(['owner_id'], ['account.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('owner_id', 'name', name='uq_workspace_owner_name')
                    )
    op.create_table('category',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('name', sa.String(length=24), nullable=False),
                    sa.Column('workspace_id', sa.BigInteger(), nullable=False),
                    sa.CheckConstraint('length(trim(name)) > 0', name='ck_category_name_not_blank'),
                    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('workspace_id', 'name', name='uq_category_workspace_name')
                    )
    op.create_table('card',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('category_id', sa.BigInteger(), nullable=False),
                    sa.Column('term', sa.String(length=255), nullable=False),
                    sa.CheckConstraint('length(trim(term)) > 0', name='ck_card_term_not_blank'),
                    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card')
    op.drop_table('category')
    op.drop_table('workspace')
    op.drop_table('account')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('settings')
    # ### end Alembic commands ###
