"""add public id to category and workspace

Revision ID: d6d6331ab9c3
Revises: ef21739e81fd
Create Date: 2026-08-27 18:29:20.739769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6d6331ab9c3'
down_revision: Union[str, Sequence[str], None] = 'ef21739e81fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    from nanoid import generate

    op.add_column('workspace', sa.Column('public_id', sa.String(length=16), nullable=True))
    op.add_column('category', sa.Column('public_id', sa.String(length=16), nullable=True))

    conn = op.get_bind()
    for table in ('workspace', 'category'):
        rows = conn.execute(sa.text(f"SELECT id FROM {table}")).fetchall()
        for (row_id,) in rows:
            conn.execute(
                sa.text(f"UPDATE {table} SET public_id = :pid WHERE id = :id"),
                {"pid": generate(size=16), "id": row_id},
            )

    op.alter_column('workspace', 'public_id', nullable=False)
    op.alter_column('category', 'public_id', nullable=False)
    op.create_index(op.f('ix_workspace_public_id'), 'workspace', ['public_id'], unique=True)
    op.create_index(op.f('ix_category_public_id'), 'category', ['public_id'], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspace_public_id'), table_name='workspace')
    op.drop_column('workspace', 'public_id')
    op.drop_index(op.f('ix_category_public_id'), table_name='category')
    op.drop_column('category', 'public_id')
    # ### end Alembic commands ###
